# 项目相关配置
nhXJH:
  # 名称
  name: nhXJH
  # 版本
  version: 3.8.1
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/nhXJH/uploadPath，Linux配置 /home/nhXJH/uploadPath）
  profile: D:/nhXJH/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
  defaultAvatar:
    url: '/profile/avatar/2022/system/default_avatar.png'
    min: 0
    max: 100

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.nhXJH: debug
    org.springframework: warn

# Spring配置
spring:
#  jpa:
#    hibernate:
#      naming-strategy: cn.studyBoot.dao.strategy.UpperTableStrategy
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  200MB
       # 设置总上传的文件大小
       max-request-size:  1000MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
#    host: localhost
    host: 
    # 端口，默认为6379
    port: 
    # 数据库索引
    database: 0
    # 密码
    password: 
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  rabbitmq:
    host: 
    port: 
    username: 
    password: 
    virtual-host: /xjh
    publisher-confirms: true
    publisher-returns: true
    # 连接超时 毫秒
    connection-timeout: 60000
    # 监听器
    listener:
      simple:
        acknowledge-mode: manual
        # 最小并发量
        concurrency: 100
        # 最大并发量
        max-concurrency: 1000
        prefetch: 50
        retry:
          # 重试是否可用
          enabled: true
      direct:
        acknowledge-mode: manual
    # 消息模板
    template:
      retry:
        enabled: true
# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌密钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 30
  
## MyBatis配置
#mybatis:
#    # 搜索指定包别名
#    typeAliasesPackage: com.nhXJH.**.domain
#    # 配置mapper的扫描，找到所有的mapper.xml映射文件
#    mapperLocations: classpath*:mapper/**/*Mapper.xml
#    # 加载全局的配置文件
#    configLocation: classpath:mybatis/mybatis-config.xml

# MyBatis Plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.nhXJH.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
#mybatis-plus:
#  type-aliases-package:
#    - com.nhXJH.**.domain
#    - com.library.**.domain.po
#    - com.file.**.domain
#  mapper-locations: classpath*:mapper/**/*Mapper.xml
#  config-location: classpath:mybatis/mybatis-config.xml



# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql 

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 本地文件上传
file:
  domain: http://127.0.0.1:9300
  path: D:/xjh/uploadPath
  prefix: /statics
  account: 98989898
  key: As#fds!12p&?xXjh

# Minio配置
minio:
  url: http://localhost:8081
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: test

# FastDFS配置
fdfs:
  domain: D:/myFile/data
  soTimeout: 3000
  connectTimeout: 2000
  trackerList: 

# 本地文件存储配置
local:
  file:
    path: D:/nhXJH/uploadPath/avatar
    maxSize: 50
    maxNameLen: 100

tokenizer:
  url: https://hanlp.hankcs.com/api

#redis配置信息
redisCache:
  #缓存超时时间
  timeOut:
    # 图书管理机构标签缓存时间 24h=86400s
    mechanismTag: 86400


picture:
  #默认图片地址
  default: /dev-api/profile/avatar/2022/system/no-picture.png
  defaultStock: /profile/avatar/2022/system/null_stock.png

#一些开关
button:
  PrecisionLoss: true #处理雪花算法造成的前后端Long精度丢失开关
  Snow: true #开启雪花算法

brow:
  book:
    timeout: 5 #图书借阅码缓存时间，分钟为单位